### ISSUE TITLE
Mise en prod :rocket: 

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#138]
- [x] Vendredi (ajd)
  - [x] Release dgfr contenant moissonneur csw-iso-dcat et indexation des datasets sans ressources [@maudetes]
- [x] Mardi matin
  - [x] MEP dgfr csw-iso-dcat + indexation 0 ressources [@maudetes]
  - [x] https://github.com/ecolabdata/ecospheres/issues/105
    - [x] Création des moissonneurs [@streino]
    - [x] Validation dans la foulée [@maudetes]
    - [x] Test mise à jour topic univers (périmètre selon [#176](https://github.com/ecolabdata/ecospheres/issues/176)/[#177](https://github.com/ecolabdata/ecospheres/issues/177)) [@streino]
  - [x] https://github.com/ecolabdata/ecospheres/issues/112 [@Thesauruv et @streino]
  - [x] https://github.com/ecolabdata/ecospheres/issues/131 [@streino]
  - [x] (si prêt) https://github.com/ecolabdata/ecospheres/issues/177 et potentiellement autres nice-to-have [@abulte]
- [x] Mardi aprem
  - [x] Mise à jour topic univers après moissonnage nouveaux endpoints [@streino]
    - [x] Feed topic
    - [x] Update `organizations` config 
  - [x] MEP ecologie.dgfr [Jo et @streino]
    - [x] Deploy demo.ecologie.dgfr
    - [x] Sanity checks
    - [x] Deploys ecologie.dgfr 
  - [x] Tests [tous ceux qui peuvent]

**Comment by streino** [comment]
ecologie.data.gouv.fr est LIVE :rocket:
