### ISSUE TITLE
Checklist avant publication

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#161]
- [x] Configuration du Matomo
- [x] Reprise du texte de la homepage
- [x] Tester le questionnaire Tally
