### ISSUE TITLE
Patches XSLT SEMICeu

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#258]
- [x] ~~Support datetime manquant~~ => https://github.com/SEMICeu/iso-19139-to-dcat-ap/issues/50
- [x] ~~Ajouter un type=Dataset en cas d'absence de type.~~ => wontdo, difficile à argumenter
- [ ] Utiliser `foaf:page` plutôt que `dcat:landingPage` par défaut -> https://github.com/SEMICeu/GeoDCAT-AP/issues/135
- [ ] Améliorer le mapping des services vers `dcat:Distribution` => https://github.com/SEMICeu/iso-19139-to-dcat-ap/issues/57
- [x] ~~[Perte du formattage de la description d'une fiche moissonnée](https://github.com/ecolabdata/ecospheres/issues/462)~~ => https://github.com/SEMICeu/iso-19139-to-dcat-ap/issues/77
- [x] ~~[Fréquences de mise à jour manquantes](https://github.com/ecolabdata/ecospheres/issues/458)~~ => https://github.com/SEMICeu/iso-19139-to-dcat-ap/issues/79
- [ ] Support `gmd:status` => https://github.com/SEMICeu/iso-19139-to-dcat-ap/issues/84
- [x] ~~Invalid geojson~~ => https://github.com/SEMICeu/iso-19139-to-dcat-ap/issues/85
- [ ] [Licences a priori valides non récupérées par data.gouv](https://github.com/ecolabdata/ecospheres/issues/861) => TBD via https://github.com/SEMICeu/GeoDCAT-AP/issues/156
