### ISSUE TITLE
Faire la liste des XSLTs préconisations

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#264]
Faire la liste des XSLTs correspondant aux préconisations destinés à passer à la "moulinette".
Un XSLT par préconisation.

Depends on #305

**Comment by Thesauruv** [comment]
A priori développements de la moulinette terminés côté Alkante.

**Comment by streino** [comment]
Liste visée pour la première itération du déploiement (oct-nov), listées par ordre de priorité de dev : 

- [x] https://github.com/ecolabdata/ecospheres/issues/352 - Ajouter le type "dataset" par défaut si manquant.
      -> Facile à faire, peu impactant => bon XSLT d'échauffement pendant la prise en main d'ISOmorophe.
- [x] https://github.com/ecolabdata/ecospheres/issues/316 - Séparer licences et conditions d'accès.
      -> Déjà démarré, bcp de discussions cet été => finir le job avant de trop oublier.
- [ ] https://github.com/ecolabdata/ecospheres/issues/355 - Identifiant de JDD valide/stable.
      -> Critique pour éviter les doublons data.gouv + (dans certains cas) correctif lien source.
- [x] https://github.com/ecolabdata/ecospheres/issues/353 - Identifier les resources de type service.
      -> Critique pour remonter les distributions + si pas de distribution, pas de license/accessRights.
- [x] https://github.com/ecolabdata/ecospheres/issues/354 - Formaliser les licences.
      -> Nice to have à ce stade (par rapport aux autres), mais fiabilisera les licences.

**Comment by streino** [comment]
@alhyss pour info
