### ISSUE TITLE
[Home] - Header

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#390]
### Todo :
**Mise à jour du header :** 

Mode connecté : 
![Image](https://github.com/user-attachments/assets/7e0aadd1-d6f2-4133-b89f-b938308816cf)

Mode déconnecté : 
![Image](https://github.com/user-attachments/assets/8174a88a-6af0-47de-8eed-524d9409813f)

- [x] En mode connecté, mise en place du lien de déconnexion et de l'affichage du nom séparé

Barre de recherche : 
 - [x] ajout de la recherche dans "Organisations" en troisième position (ordre : jeux de données, bouquets, organisations)
 - [ ] reprise du composant recherche développé pour le RGAA

**Comment by at-github** [comment]
Pour le changement de comportement du bouton, à priori, il faut refaire un composant maison, vous êtes d'accord @abulte & @narduin ?

**Comment by abulte** [comment]
Il faut faire le lien avec https://github.com/opendatateam/udata-front-kit/pull/539#pullrequestreview-2360825280 @thomas-duport @DanFluture275 — on a en prod une version du champ de recherche qui a été faite il y a quelques jours et qui ne correspond pas aux maquettes.

**Comment by narduin** [comment]
Tu peux t'aider du point 14 du rapport d'audit RGAA si besoin @at-github !

**Comment by at-github** [comment]
Je prend connaissance du code, je me suis fait avoir par la condition dropdown.
Effectivement j'ai un input "maison" et un composant dsfr…
Ce ticket a un peu plus d'implication que ce que je pensais

**Comment by DanFluture275** [comment]
@thomas-duport préconise de rester sur un composant du design system de l'état pour ce champs de recherche.

**Comment by abulte** [comment]
> @thomas-duport préconise de rester sur un composant du design system de l'état pour ce champs de recherche.

~~Juste ce champ (home central) ou les deux ?~~

~~Si juste ce champ, ça veut dire développer deux composants complexes différents pour la même fonctionnalité.~~

(My bad, on ne parle pas du champ central ici, mais il faudra se poser la question vu que c'est la même fonctionnalité).

Et si pas juste ce champ, il aurait fallu arbitrer sur https://github.com/opendatateam/udata-front-kit/pull/539. Et voir comment on le rend accessible si on revient en arrière.

**Comment by at-github** [comment]
@abulte @DanFluture275 je commence une nouvelle tâche en attendant que cette conversation aboutisse ?

**Comment by at-github** [comment]
J'ai ferré à droite le menu, pour que l'icone soit aligné avec le bord du champ de recherche

**Comment by narduin** [comment]
@thomas-duport c'est fait exprès l'icône de déconnexion qui reste la même pour "se connecter" ?

**Comment by at-github** [comment]
@DanFluture275 Sur remarque de @abulte je retire organisation du menu déroulant, la page organisations n'étant pas prête avec la recherche associé, en review la décision est prise de le retirer.

**Comment by ghost** [comment]
My bad @narduin c'est bon c'est à jour
